controller_list:
  - name: fake_Arm_controller
    joints:
      - shoulder_pitch_joint
      - elbow_flex_joint
      - wrist_roll_joint
  - name: fake_Gripper_controller
    joints:
      - claw_joint